<?php

namespace App\Services;

use App\Services\Niches\NichesCityCatalog;
use App\Services\Niches\NichesTaxonomyParser;

class NichesBootstrapSteps
{
    public function __construct(
        private GooglePlacesService $places,
        private NichesTaxonomyParser $taxonomy,
    ) {}

    /**
     * @param  callable(string): void|null  $warn
     * @return list<string>
     */
    public function fetchCities(?callable $warn = null): array
    {
        return (new NichesCityCatalog)->fetchCities($warn);
    }

    /**
     * @param  callable(string): void|null  $warn
     * @return list<array{label: string, query: string, primary_type: string}>
     */
    public function fetchNicheCandidates(?callable $warn = null): array
    {
        return $this->taxonomy->fetchCandidates($warn);
    }

    /**
     * @param  list<array{label: string, query: string, primary_type: string}>  $niches
     * @param  callable(string): void|null  $warn
     * @param  callable(): void|null  $advance
     * @return array{niches: list<array{label: string, query: string, primary_type: string}>, apiCalls: int, dropped: int, keptUnvalidated: bool}
     */
    public function validateNiches(array $niches, int $minResults, ?callable $warn = null, ?callable $advance = null): array
    {
        $key = config('services.google_places.key');

        if ($key === null || $key === '') {
            if ($warn !== null) {
                $warn('GOOGLE_PLACES_API_KEY is not set; skipping validation pass.');
            }

            return ['niches' => $niches, 'apiCalls' => 0, 'dropped' => 0, 'keptUnvalidated' => false];
        }

        $minResults = max(1, $minResults);
        $kept = [];
        $dropped = 0;
        $apiCalls = 0;
        $zeroResultCount = 0;

        foreach ($niches as $niche) {
            $apiCalls++;
            $placeIds = $this->places->searchByNicheAndCity($niche['query'], 'Birmingham', 'GB');
            $count = count($placeIds);

            if ($count === 0) {
                $zeroResultCount++;
            }

            if ($count < $minResults) {
                $dropped++;
                if ($warn !== null) {
                    $warn("Dropped {$niche['label']}: {$count} results in Birmingham");
                }
            } else {
                $kept[] = $niche;
            }

            if ($advance !== null) {
                $advance();
            }
        }

        if ($zeroResultCount === count($niches) && count($niches) > 0) {
            if ($warn !== null) {
                $warn('Places API may have failed — keeping unvalidated niche list.');
            }

            return ['niches' => $niches, 'apiCalls' => $apiCalls, 'dropped' => 0, 'keptUnvalidated' => true];
        }

        return ['niches' => $kept, 'apiCalls' => $apiCalls, 'dropped' => $dropped, 'keptUnvalidated' => false];
    }

    /**
     * @param  list<array{label: string, query: string, primary_type: string}>  $niches
     * @param  list<string>  $cities
     */
    public function renderConfigPhp(array $niches, array $cities): string
    {
        $date = now()->toDateString();
        $export = var_export(['niches' => $niches, 'cities' => $cities], true);

        return <<<PHP
<?php

// Generated by niches:bootstrap on {$date}
// Edit this file manually to add, remove, or rename niches.
// Re-run niches:bootstrap only if you need to expand from scratch.

return {$export};

PHP;
    }
}
