<?php

namespace App\Http\Controllers;

use App\Models\NicheScan;
use App\Services\ApiHealthService;
use App\Services\UserSettingsService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Inertia\Inertia;
use Inertia\Response;

class SettingsController extends Controller
{
    public function index(Request $request, ApiHealthService $health, UserSettingsService $settings): Response
    {
        $setting = $settings->forUser($request->user());
        $lastScan = NicheScan::query()->orderByDesc('ran_at')->first()?->ran_at;

        return Inertia::render('Settings/Index', [
            'settings' => [
                'default_country' => $setting->default_country,
                'agency_name'     => $setting->agency_name ?? '',
                'booking_url'     => $setting->booking_url ?? '',
            ],
            'nicheMaintenance' => [
                'niche_count'      => count(config('niches.niches', [])),
                'city_count'       => count(config('niches.cities', [])),
                'last_scan_at'     => $lastScan?->toISOString(),
                'last_scan_human'  => $lastScan ? $lastScan->diffForHumans() : 'Never',
                'config_generated' => self::parseNichesConfigDate(),
            ],
            'health' => $health->checkAll(),
            'env'    => [
                'reports_disk'      => config('scanner.reports_disk', 'public'),
                'audit_driver'      => config('scanner.audit_driver'),
                'screenshot_driver' => config('scanner.screenshot_driver'),
            ],
        ]);
    }

    public function update(Request $request, UserSettingsService $settings): RedirectResponse
    {
        $validated = $request->validate([
            'default_country' => 'required|string|size:2',
            'agency_name'     => 'nullable|string|max:100',
            'booking_url'     => 'nullable|url|max:255',
        ]);

        $setting = $settings->forUser($request->user());
        $setting->update($validated);

        return back()->with('success', 'Settings saved.');
    }

    public function scanNiches(Request $request): RedirectResponse
    {
        $validated = $request->validate([
            'force' => 'sometimes|boolean',
        ]);

        $params = ! empty($validated['force']) ? ['--force' => true] : [];

        Artisan::queue('niches:scan', $params);

        return back()->with('success', 'Market scan queued.');
    }

    public function bootstrapNiches(Request $request): RedirectResponse
    {
        $request->validate([
            'confirm' => 'required|in:REFRESH',
        ]);

        Artisan::queue('niches:bootstrap', [
            '--no-interaction' => true,
            '--force'          => true,
        ]);

        return back()->with('success', 'Catalog refresh queued.');
    }

    private static function parseNichesConfigDate(): ?string
    {
        $path = config_path('niches.php');

        if (! is_readable($path)) {
            return null;
        }

        $header = file_get_contents($path, false, null, 0, 512);

        if ($header === false) {
            return null;
        }

        if (preg_match('/Generated by niches:bootstrap on (\d{4}-\d{2}-\d{2})/', $header, $matches)) {
            return $matches[1];
        }

        return null;
    }
}
